apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    variant: lab
namePrefix: lab-
namespace: argocd
resources:
- nginx-3267.argocd.yaml
- nginx-3306.argocd.yaml
