web:
  image:
    repository: docker pull ghcr.io/104corp/nfs-pull
    tag: v2
  nfs:
  - claimName: l-presentation-nginx-3267-models
    mountPath: /data
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    enabled: true
    hosts:
      - host: nginx-3267
        paths:
          - path: /
            pathType: ImplementationSpecific
            svcPort: 80
  extraContainers:
    - name: network-tools
      image: 
        repository: ghcr.io/104corp/network-tools
        tag: v1
      command: ["sh", "-c", "tail -f /dev/null"]
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
