web:
  image:
    repository: ghcr.io/104corp/bitnami/nginx
    tag: 1.24.0
  extraContainers:
  - name: nodejs
    image:
      repository: ghcr.io/104corp/nodejs
      tag: v1
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
