web:
  image:
    repository: ghcr.io/104corp/nfs-pull
    tag: v4
  nfs:
  - claimName: l-presentation-nginx-3267-models
    mountPath: /data
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    enabled: true
    hosts:
      - host: nginx-3267
        paths:
          - path: /
            pathType: ImplementationSpecific
            svcPort: 80
  readinessProbe: # 偵測應用程式是否 ready
    enabled: true
    initialDelaySeconds: 5  # 延遲開始確認時間
    periodSeconds: 60       # 每 N 秒打一次
    timeoutSeconds: 5       # N 秒逾時
    successThreshold: 1     # 若成功回應一次就算本次成功
    failureThreshold: 3     # 重試三次後才算失敗
    httpGet:
      path: /health
      port: 8080
  livenessProbe: # 偵測應用程式是否正常運行
    enabled: true
    initialDelaySeconds: 5  # 延遲開始確認時間
    periodSeconds: 60       # 每 N 秒打一次
    timeoutSeconds: 3       # N 秒逾時
    successThreshold: 1     # 若成功回應一次就算本次成功
    failureThreshold: 3     # 重試三次後才算失敗
    httpGet:
      path: /health
      port: 8080
  extraContainers:
    - name: network-tools
      image: 
        repository: ghcr.io/104corp/network-tools
        tag: v1
      command: ["sh", "-c", "tail -f /dev/null"]
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
