web:
  image:
    repository: ghcr.io/104corp/nodejs
    tag: v1
  extraContainers:
  - name: nginx
    image:
      repository: ghcr.io/104corp/bitnami/nginx
      tag: 1.24.0
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    ports:
    - containerPort: 8000
      protocol: TCP
      name: nginx
